# UCL AI Society Machine Learning Tutorials
### Session 01. Introduction to Numpy, Pandas and Matplotlib Libraries

### Contents
1. Numpy
2. Pandas
3. Matplotlib
4. EDA(Exploratory Data Analysis)

### Aim
At the end of this session, you will be able to:
- Understand the basics of numpy.
- Understand the basics of pandas.
- Understand the basics of matplotlib.
- Build a simple EDA using above libraries.

## 2. Pandas
Pandas is another essential open-source library of Python and today widely used by data scientists and analysts. Wes McKinney built it on the numpy to transform and analyze data. According to the Wikipedia, It is derived from the term "Panel Data", an econometrics term for data sets that include observations over multiple time periods for the same individuals.

### 2.1 Basics of Pandas

In [1]:
# run this shell if you haven't install pandas library
! pip install pandas

Requirement already satisfied: pandas in c:\users\hjkoo\anaconda3\lib\site-packages (0.24.2)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\hjkoo\anaconda3\lib\site-packages (from pandas) (2.8.0)
Requirement already satisfied: numpy>=1.12.0 in c:\users\hjkoo\anaconda3\lib\site-packages (from pandas) (1.16.2)
Requirement already satisfied: pytz>=2011k in c:\users\hjkoo\anaconda3\lib\site-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in c:\users\hjkoo\anaconda3\lib\site-packages (from python-dateutil>=2.5.0->pandas) (1.12.0)

In [2]:
import pandas as pd
import numpy as np

In [3]:
print(pd.__version__)

0.24.2

The main data structures of pandas are **Series** and **DataFrames**, where data are stored and manipulated. A `Series` is a column and a `DataFrame` is a multi-dimensional table consisted of a collection of Series.

In [4]:
a = pd.Series([1, 2, 3, np.nan, 5, 6])

In [5]:
print(a)

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
5    6.0
dtype: float64

In [6]:
b = {
    'Name' : ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"],
    'Satellite' : [0, 0, 1, 2, 79, 60, 27, 14],
    'AU' : [0.4, 0.7, 1, 1.5, 5.2, 9.5, 19.2, 30.1],
    'Diameter (in 1Kkm)' : [4.9, 12.1, 12.7, 6.8, 139.8, 116.5, 50.7, 49.2]
}

In [7]:
solar_system = pd.DataFrame(b, index = [i for i in range(1, 9)])
solar_system

      Name  Satellite    AU  Diameter (in 1Kkm)
1  Mercury          0   0.4                 4.9
2    Venus          0   0.7                12.1
3    Earth          1   1.0                12.7
4     Mars          2   1.5                 6.8
5  Jupiter         79   5.2               139.8
6   Saturn         60   9.5               116.5
7   Uranus         27  19.2                50.7
8  Neptune         14  30.1                49.2

In [8]:
solar_system.dtypes # check data type

Name                   object
Satellite               int64
AU                    float64
Diameter (in 1Kkm)    float64
dtype: object

We can select what to read from the DataFrame
- `head()` : Extracts the first few data
- `tail()` : Extracts the last few data
- `index` : Extracts the index
- `columns` : Extracts the column
- `loc` : Extracts the information of that row
- `values` : Extracts only the values
- `describe()` : Outputs the summary of statistics of DataFrame
- `sort_values(self, by, axis = 0, ascending = True, inplace = False)` : Sort the DataFrame
- `drop()` : Drop the selected row

In [9]:
df = solar_system

In [10]:
df.head() # the default value in the bracket is 5

      Name  Satellite   AU  Diameter (in 1Kkm)
1  Mercury          0  0.4                 4.9
2    Venus          0  0.7                12.1
3    Earth          1  1.0                12.7
4     Mars          2  1.5                 6.8
5  Jupiter         79  5.2               139.8

In [11]:
df.tail(2)

      Name  Satellite    AU  Diameter (in 1Kkm)
7   Uranus         27  19.2                50.7
8  Neptune         14  30.1                49.2

In [12]:
df.index

Int64Index([1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')

In [13]:
df.columns

Index(['Name', 'Satellite', 'AU', 'Diameter (in 1Kkm)'], dtype='object')

In [14]:
df.loc[4]

Name                  Mars
Satellite                2
AU                     1.5
Diameter (in 1Kkm)     6.8
Name: 4, dtype: object

In [15]:
df.values

array([['Mercury', 0, 0.4, 4.9],
       ['Venus', 0, 0.7, 12.1],
       ['Earth', 1, 1.0, 12.7],
       ['Mars', 2, 1.5, 6.8],
       ['Jupiter', 79, 5.2, 139.8],
       ['Saturn', 60, 9.5, 116.5],
       ['Uranus', 27, 19.2, 50.7],
       ['Neptune', 14, 30.1, 49.2]], dtype=object)

In [16]:
df.describe()

       Satellite         AU  Diameter (in 1Kkm)
count   8.000000   8.000000             8.00000
mean   22.875000   8.450000            49.08750
std    30.670775  10.853702            52.38417
min     0.000000   0.400000             4.90000
25%     0.750000   0.925000            10.77500
50%     8.000000   3.350000            30.95000
75%    35.250000  11.925000            67.15000
max    79.000000  30.100000           139.80000

In [17]:
df.sort_values(by = 'Diameter (in 1Kkm)', ascending = False)

      Name  Satellite    AU  Diameter (in 1Kkm)
5  Jupiter         79   5.2               139.8
6   Saturn         60   9.5               116.5
7   Uranus         27  19.2                50.7
8  Neptune         14  30.1                49.2
3    Earth          1   1.0                12.7
2    Venus          0   0.7                12.1
4     Mars          2   1.5                 6.8
1  Mercury          0   0.4                 4.9

In [18]:
# TO DO: re-sort the DataFrame by the number of satellite in the decreasing order.
df.sort_values(by = 'Satellite', ascending = False)

      Name  Satellite    AU  Diameter (in 1Kkm)
5  Jupiter         79   5.2               139.8
6   Saturn         60   9.5               116.5
7   Uranus         27  19.2                50.7
8  Neptune         14  30.1                49.2
4     Mars          2   1.5                 6.8
3    Earth          1   1.0                12.7
1  Mercury          0   0.4                 4.9
2    Venus          0   0.7                12.1

Before 2016, Pluto was classified as a planet of the solar system. Let's add Pluto to our DataFrame.

In [19]:
df.loc[9] = ["Pluto", 0, 39.5, 2.38]
df

      Name  Satellite    AU  Diameter (in 1Kkm)
1  Mercury          0   0.4                4.90
2    Venus          0   0.7               12.10
3    Earth          1   1.0               12.70
4     Mars          2   1.5                6.80
5  Jupiter         79   5.2              139.80
6   Saturn         60   9.5              116.50
7   Uranus         27  19.2               50.70
8  Neptune         14  30.1               49.20
9    Pluto          0  39.5                2.38

Let's excludeit again as it is regraded as a dwarf planet in the field of astronomy.

In [20]:
# Even if the index of Pluto was 9, it is regarded as 8, as the index starts from 0
df.drop(df.index[8])

      Name  Satellite    AU  Diameter (in 1Kkm)
1  Mercury          0   0.4                 4.9
2    Venus          0   0.7                12.1
3    Earth          1   1.0                12.7
4     Mars          2   1.5                 6.8
5  Jupiter         79   5.2               139.8
6   Saturn         60   9.5               116.5
7   Uranus         27  19.2                50.7
8  Neptune         14  30.1                49.2

### 2.2 Read Data via Pandas
Pandas supports loading, reading, and writing data from various file format, including CSV, JSON and SQL, by converting it to a DataFrame. 
1. `pd.read_csv()` : Read CSV files
2. `pd.read_json()` : Read JSON files
3. `pd.read_sql_query()` : Read SQL files

In [21]:
# download data at https://support.spatialkey.com/spatialkey-sample-csv-data/
movie = pd.read_csv("./data/IMDB-Movie-Data.csv", index_col = "Title")
movie

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
The Great Wall,6,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
La La Land,7,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
Mindhorn,8,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
The Lost City of Z,9,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
Passengers,10,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0
Fantastic Beasts and Where to Find Them,11,"Adventure,Family,Fantasy",The adventures of writer Newt Scamander in New...,David Yates,"Eddie Redmayne, Katherine Waterston, Alison Su...",2016,133,7.5,232072,234.02,66.0
Hidden Figures,12,"Biography,Drama,History",The story of a team of female African-American...,Theodore Melfi,"Taraji P. Henson, Octavia Spencer, Janelle Mon...",2016,127,7.8,93103,169.27,74.0
Rogue One,13,"Action,Adventure,Sci-Fi",The Rebel Alliance makes a risky move to steal...,Gareth Edwards,"Felicity Jones, Diego Luna, Alan Tudyk, Donnie...",2016,133,7.9,323118,532.17,65.0
Moana,14,"Animation,Adventure,Comedy","In Ancient Polynesia, when a terrible curse in...",Ron Clements,"Auli'i Cravalho, Dwayne Johnson, Rachel House,...",2016,107,7.7,118151,248.75,81.0
Colossal,15,"Action,Comedy,Drama",Gloria is an out-of-work party girl forced to ...,Nacho Vigalondo,"Anne Hathaway, Jason Sudeikis, Austin Stowell,...",2016,109,6.4,8612,2.87,70.0
The Secret Life of Pets,16,"Animation,Adventure,Comedy",The quiet life of a terrier named Max is upend...,Chris Renaud,"Louis C.K., Eric Stonestreet, Kevin Hart, Lake...",2016,87,6.6,120259,368.31,61.0
Hacksaw Ridge,17,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0
Jason Bourne,18,"Action,Thriller",The CIA's most dangerous former operative is d...,Paul Greengrass,"Matt Damon, Tommy Lee Jones, Alicia Vikander,V...",2016,123,6.7,150823,162.16,58.0
Lion,19,"Biography,Drama",A five-year-old Indian boy gets lost on the st...,Garth Davis,"Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...",2016,118,8.1,102061,51.69,69.0
Arrival,20,"Drama,Mystery,Sci-Fi",When twelve mysterious spacecraft appear aroun...,Denis Villeneuve,"Amy Adams, Jeremy Renner, Forest Whitaker,Mich...",2016,116,8.0,340798,100.50,81.0
Gold,21,"Adventure,Drama,Thriller","Kenny Wells, a prospector desperate for a luck...",Stephen Gaghan,"Matthew McConaughey, Edgar Ramírez, Bryce Dall...",2016,120,6.7,19053,7.22,49.0
Manchester by the Sea,22,Drama,A depressed uncle is asked to take care of his...,Kenneth Lonergan,"Casey Affleck, Michelle Williams, Kyle Chandle...",2016,137,7.9,134213,47.70,96.0
Hounds of Love,23,"Crime,Drama,Horror",A cold-blooded predatory couple while cruising...,Ben Young,"Emma Booth, Ashleigh Cummings, Stephen Curry,S...",2016,108,6.7,1115,NaN,72.0
Trolls,24,"Animation,Adventure,Comedy","After the Bergens invade Troll Village, Poppy,...",Walt Dohrn,"Anna Kendrick, Justin Timberlake,Zooey Deschan...",2016,92,6.5,38552,153.69,56.0
Independence Day: Resurgence,25,"Action,Adventure,Sci-Fi",Two decades after the first Independence Day i...,Roland Emmerich,"Liam Hemsworth, Jeff Goldblum, Bill Pullman,Ma...",2016,120,5.3,127553,103.14,32.0
Paris pieds nus,26,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,NaN,NaN
Bahubali: The Beginning,27,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,NaN
Dead Awake,28,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN
Bad Moms,29,Comedy,When three overworked and under-appreciated mo...,Jon Lucas,"Mila Kunis, Kathryn Hahn, Kristen Bell,Christi...",2016,100,6.2,66540,113.08,60.0
Assassin's Creed,30,"Action,Adventure,Drama",When Callum Lynch explores the memories of his...,Justin Kurzel,"Michael Fassbender, Marion Cotillard, Jeremy I...",2016,115,5.9,112813,54.65,36.0
...,...,...,...,...,...,...,...,...,...,...,...
Texas Chainsaw 3D,971,"Horror,Thriller",A young woman travels to Texas to collect an i...,John Luessenhop,"Alexandra Daddario, Tania Raymonde, Scott East...",2013,92,4.8,37060,34.33,62.0
Disturbia,972,"Drama,Mystery,Thriller",A teen living under house arrest becomes convi...,D.J. Caruso,"Shia LaBeouf, David Morse, Carrie-Anne Moss, S...",2007,105,6.9,193491,80.05,NaN
Rock of Ages,973,"Comedy,Drama,Musical",A small town girl and a city boy meet on the S...,Adam Shankman,"Julianne Hough, Diego Boneta, Tom Cruise, Alec...",2012,123,5.9,64513,38.51,47.0
Scream 4,974,"Horror,Mystery","Ten years have passed, and Sidney Prescott, wh...",Wes Craven,"Neve Campbell, Courteney Cox, David Arquette, ...",2011,111,6.2,108544,38.18,52.0
Queen of Katwe,975,"Biography,Drama,Sport",A Ugandan girl sees her world rapidly change a...,Mira Nair,"Madina Nalwanga, David Oyelowo, Lupita Nyong'o...",2016,124,7.4,6753,8.81,73.0
My Big Fat Greek Wedding 2,976,"Comedy,Family,Romance",A Portokalos family secret brings the beloved ...,Kirk Jones,"Nia Vardalos, John Corbett, Michael Constantin...",2016,94,6.0,20966,59.57,37.0
Dark Places,977,"Drama,Mystery,Thriller",Libby Day was only eight years old when her fa...,Gilles Paquet-Brenner,"Charlize Theron, Nicholas Hoult, Christina Hen...",2015,113,6.2,31634,NaN,39.0
Amateur Night,978,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,NaN,38.0
It's Only the End of the World,979,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,NaN,48.0
The Skin I Live In,980,"Drama,Thriller","A brilliant plastic surgeon, haunted by past t...",Pedro Almodóvar,"Antonio Banderas, Elena Anaya, Jan Cornet,Mari...",2011,120,7.6,108772,3.19,70.0
Miracles from Heaven,981,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0
Annie,982,"Comedy,Drama,Family","A foster kid, who lives with her mean foster m...",Will Gluck,"Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...",2014,118,5.3,27312,85.91,33.0
Across the Universe,983,"Drama,Fantasy,Musical",The music of the Beatles and the Vietnam War f...,Julie Taymor,"Evan Rachel Wood, Jim Sturgess, Joe Anderson, ...",2007,133,7.4,95172,24.34,56.0
Let's Be Cops,984,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.39,30.0
Max,985,"Adventure,Family",A Malinois dog that helped American Marines in...,Boaz Yakin,"Thomas Haden Church, Josh Wiggins, Luke Kleint...",2015,111,6.8,21405,42.65,47.0
Your Highness,986,"Adventure,Comedy,Fantasy","When Prince Fabious's bride is kidnapped, he g...",David Gordon Green,"Danny McBride, Natalie Portman, James Franco, ...",2011,102,5.6,87904,21.56,31.0
Final Destination 5,987,"Horror,Thriller",Survivors of a suspension-bridge collapse lear...,Steven Quale,"Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...",2011,92,5.9,88000,42.58,50.0
Endless Love,988,"Drama,Romance",The story of a privileged girl and a charismat...,Shana Feste,"Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...",2014,104,6.3,33688,23.39,30.0
Martyrs,989,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,NaN,89.0
Selma,990,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,NaN
Underworld: Rise of the Lycans,991,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.80,44.0
Taare Zameen Par,992,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0
Take Me Home Tonight,993,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN
Resident Evil: Afterlife,994,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
Project X,995,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [22]:
# To Do: Extract the information of the movie that has the rank of 3
movie.iloc[2]

Rank                                                                  3
Genre                                                   Horror,Thriller
Description           Three girls are kidnapped by a man with a diag...
Director                                             M. Night Shyamalan
Actors                James McAvoy, Anya Taylor-Joy, Haley Lu Richar...
Year                                                               2016
Runtime (Minutes)                                                   117
Rating                                                              7.3
Votes                                                            157606
Revenue (Millions)                                               138.12
Metascore                                                            62
Name: Split, dtype: object

In [23]:
# To Do: Re-sort the table in terms of Rating, in the decreasing order
movie.sort_values(by = "Rating", ascending = False)

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
The Dark Knight,55,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
Inception,81,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0
Dangal,118,"Action,Biography,Drama",Former wrestler Mahavir Singh Phogat and his t...,Nitesh Tiwari,"Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...",2016,161,8.8,48969,11.15,NaN
Interstellar,37,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
Kimi no na wa,97,"Animation,Drama,Fantasy",Two strangers find themselves linked in a biza...,Makoto Shinkai,"Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Nari...",2016,106,8.6,34110,4.68,79.0
The Intouchables,250,"Biography,Comedy,Drama",After he becomes a quadriplegic from a paragli...,Olivier Nakache,"François Cluzet, Omar Sy, Anne Le Ny, Audrey F...",2011,112,8.6,557965,13.18,57.0
Whiplash,134,"Drama,Music",A promising young drummer enrolls at a cut-thr...,Damien Chazelle,"Miles Teller, J.K. Simmons, Melissa Benoist, P...",2014,107,8.5,477276,13.09,88.0
The Prestige,65,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66.0
The Departed,100,"Crime,Drama,Thriller",An undercover cop and a mole in the police att...,Martin Scorsese,"Leonardo DiCaprio, Matt Damon, Jack Nicholson,...",2006,151,8.5,937414,132.37,85.0
Taare Zameen Par,992,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0
The Dark Knight Rises,125,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.0
The Lives of Others,477,"Drama,Thriller","In 1984 East Berlin, an agent of the secret po...",Florian Henckel von Donnersmarck,"Ulrich Mühe, Martina Gedeck,Sebastian Koch, Ul...",2006,137,8.5,278103,11.28,89.0
WALL·E,635,"Animation,Adventure,Family","In the distant future, a small waste-collectin...",Andrew Stanton,"Ben Burtt, Elissa Knight, Jeff Garlin, Fred Wi...",2008,98,8.4,776897,223.81,NaN
3 Idiots,431,"Comedy,Drama",Two friends are searching for their long lost ...,Rajkumar Hirani,"Aamir Khan, Madhavan, Mona Singh, Sharman Joshi",2009,170,8.4,238789,6.52,67.0
Koe no katachi,862,"Animation,Drama,Romance","The story revolves around Nishimiya Shoko, a g...",Naoko Yamada,"Miyu Irino, Saori Hayami, Aoi Yuki, Kenshô Ono",2016,129,8.4,2421,NaN,80.0
Django Unchained,145,"Drama,Western","With the help of a German bounty hunter , a fr...",Quentin Tarantino,"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio...",2012,165,8.4,1039115,162.80,81.0
La La Land,7,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
Jagten,456,Drama,"A teacher lives a lonely life, all the while s...",Thomas Vinterberg,"Mads Mikkelsen, Thomas Bo Larsen, Annika Wedde...",2012,115,8.3,192263,0.61,76.0
Up,500,"Animation,Adventure,Comedy",Seventy-eight year old Carl Fredricksen travel...,Pete Docter,"Edward Asner, Jordan Nagai, John Ratzenberger,...",2009,96,8.3,722203,292.98,88.0
Inglourious Basterds,78,"Adventure,Drama,War","In Nazi-occupied France during World War II, a...",Quentin Tarantino,"Brad Pitt, Diane Kruger, Eli Roth,Mélanie Laurent",2009,153,8.3,959065,120.52,69.0
Toy Story 3,689,"Animation,Adventure,Comedy",The toys are mistakenly delivered to a day-car...,Lee Unkrich,"Tom Hanks, Tim Allen, Joan Cusack, Ned Beatty",2010,103,8.3,586669,414.98,92.0
Paint It Black,479,Drama,A young woman attempts to deal with the death ...,Amber Tamblyn,"Alia Shawkat, Nancy Kwan, Annabelle Attanasio,...",2016,96,8.3,61,NaN,71.0
Bahubali: The Beginning,27,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,NaN
PK,766,"Comedy,Drama,Romance",A stranger in the city asks questions no one h...,Rajkumar Hirani,"Aamir Khan, Anushka Sharma, Sanjay Dutt,Boman ...",2014,153,8.2,103279,10.57,51.0
The Wolf of Wall Street,83,"Biography,Comedy,Crime","Based on the true story of Jordan Belfort, fro...",Martin Scorsese,"Leonardo DiCaprio, Jonah Hill, Margot Robbie,M...",2013,180,8.2,865134,116.87,75.0
Inside Out,242,"Animation,Adventure,Comedy",After young Riley is uprooted from her Midwest...,Pete Docter,"Amy Poehler, Bill Hader, Lewis Black, Mindy Ka...",2015,95,8.2,416689,356.45,94.0
Gran Torino,646,Drama,Disgruntled Korean War veteran Walt Kowalski s...,Clint Eastwood,"Clint Eastwood, Bee Vang, Christopher Carley,A...",2008,116,8.2,595779,148.09,NaN
Incendies,714,"Drama,Mystery,War",Twins journey to the Middle East to discover t...,Denis Villeneuve,"Lubna Azabal, Mélissa Désormeaux-Poulin, Maxim...",2010,131,8.2,92863,6.86,80.0
El secreto de sus ojos,743,"Drama,Mystery,Romance",A retired legal counselor writes a novel hopin...,Juan José Campanella,"Ricardo Darín, Soledad Villamil, Pablo Rago,Ca...",2009,129,8.2,144524,20.17,80.0
Hacksaw Ridge,17,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0
...,...,...,...,...,...,...,...,...,...,...,...
Final Girl,778,"Action,Thriller",A man teaches a young woman how to become a co...,Tyler Shields,"Abigail Breslin, Wes Bentley, Logan Huffman,Al...",2015,90,4.7,9026,NaN,56.0
Dead Awake,28,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN
Viking,523,"Action,Drama,History","Kievan Rus, late 10th century. After the death...",Andrey Kravchuk,"Anton Adasinsky, Aleksandr Armer, Vilen Babich...",2016,133,4.7,1830,23.05,57.0
Zoolander 2,432,Comedy,Derek and Hansel are lured into modeling again...,Ben Stiller,"Ben Stiller, Owen Wilson, Penélope Cruz, Will ...",2016,102,4.7,48297,28.84,34.0
The Boy Next Door,556,"Mystery,Thriller","A woman, separated from her unfaithful husband...",Rob Cohen,"Jennifer Lopez, Ryan Guzman, Kristin Chenoweth...",2015,91,4.6,30180,35.39,30.0
Wolves at the Door,820,"Horror,Thriller",Four friends gather at an elegant home during ...,John R. Leonetti,"Katie Cassidy, Elizabeth Henstridge, Adam Camp...",2016,73,4.6,564,NaN,63.0
Max Steel,788,"Action,Adventure,Family",The adventures of teenager Max McGrath and his...,Stewart Hendler,"Ben Winchell, Josh Brener, Maria Bello, Andy G...",2016,92,4.6,11555,3.77,22.0
Only for One Night,747,Thriller,A married womans husband with a perfect life c...,Chris Stokes,"Brian White, Karrueche Tran, Angelique Pereira...",2016,86,4.6,313,NaN,60.0
Shut In,827,"Drama,Horror,Thriller",A heart-pounding thriller about a widowed chil...,Farren Blackburn,"Naomi Watts, Charlie Heaton, Jacob Tremblay,Ol...",2016,91,4.6,5715,6.88,NaN
The Assignment,772,"Action,Crime,Thriller",After waking up and discovering that he has un...,Walter Hill,"Sigourney Weaver, Michelle Rodriguez, Tony Sha...",2016,95,4.5,2043,NaN,34.0
The Human Centipede (First Sequence),937,Horror,A mad scientist kidnaps and mutilates a trio o...,Tom Six,"Dieter Laser, Ashley C. Williams, Ashlynn Yenn...",2009,92,4.4,60655,0.18,33.0
Sex and the City 2,953,"Comedy,Drama,Romance","While wrestling with the pressures of life, lo...",Michael Patrick King,"Sarah Jessica Parker, Kim Cattrall, Kristin Da...",2010,146,4.3,62403,95.33,27.0
Yoga Hosers,801,"Comedy,Fantasy,Horror",Two teenage yoga enthusiasts team up with a le...,Kevin Smith,"Lily-Rose Depp, Harley Quinn Smith, Johnny Dep...",2016,88,4.3,7091,NaN,23.0
Movie 43,509,"Comedy,Romance",A series of interconnected short films follows...,Elizabeth Banks,"Emma Stone, Stephen Merchant, Richard Gere, Li...",2013,94,4.3,83625,8.83,18.0
Fantastic Four,553,"Action,Adventure,Sci-Fi",Four young outsiders teleport to an alternate ...,Josh Trank,"Miles Teller, Kate Mara, Michael B. Jordan, Ja...",2015,100,4.3,121847,56.11,27.0
Exposed,839,"Crime,Drama,Mystery",A police detective investigates the truth behi...,Gee Malik Linton,"Ana de Armas, Keanu Reeves, Christopher McDona...",2016,102,4.2,8409,NaN,23.0
The Last Airbender,582,"Action,Adventure,Family","Follows the adventures of Aang, a young succes...",M. Night Shyamalan,"Noah Ringer, Nicola Peltz, Jackson Rathbone,De...",2010,103,4.2,125129,NaN,20.0
Fifty Shades of Grey,64,"Drama,Romance,Thriller",Literature student Anastasia Steele's life cha...,Sam Taylor-Johnson,"Dakota Johnson, Jamie Dornan, Jennifer Ehle,El...",2015,125,4.1,244474,166.15,46.0
2307: Winter's Dream,617,Sci-Fi,"In 2307, a future soldier is sent on a mission...",Joey Curtis,"Paul Sidhu, Branden Coles, Arielle Holmes, Kel...",2016,101,4.0,277,20.76,53.0
The Disappointments Room,238,"Drama,Horror,Thriller",A mother and her young son release unimaginabl...,D.J. Caruso,"Kate Beckinsale, Mel Raido, Duncan Joiner, Luc...",2016,85,3.9,4895,2.41,31.0
The Black Room,402,Horror,PAUL and JENNIFER HEMDALE have just moved into...,Rolfe Kanefsky,"Natasha Henstridge, Lukas Hassel, Lin Shaye,Do...",2016,91,3.9,240,NaN,71.0
Birth of the Dragon,526,"Action,Biography,Drama","Young, up-and-coming martial artist, Bruce Lee...",George Nolfi,"Billy Magnussen, Terry Chen, Teresa Navarro,Va...",2016,103,3.9,552,93.05,61.0
Satanic,270,Horror,Four friends on their way to Coachella stop of...,Jeffrey G. Hunt,"Sarah Hyland, Steven Krueger, Justin Chon, Cla...",2016,85,3.7,2384,NaN,NaN
The Last Face,50,Drama,A director (Charlize Theron) of an internation...,Sean Penn,"Charlize Theron, Javier Bardem, Adèle Exarchop...",2016,130,3.7,987,NaN,16.0
The Intent,891,"Crime,Drama",Gunz (Dylan Duffus) is thrust into a world of ...,Femi Oyeniran,"Dylan Duffus, Scorcher,Shone Romulus, Jade Asha",2016,104,3.5,202,NaN,59.0
Wrecker,969,"Action,Horror,Thriller",Best friends Emily and Lesley go on a road tri...,Micheal Bafaro,"Anna Hutchison, Andrea Whitburn, Jennifer Koen...",2015,83,3.5,1210,NaN,37.0
Tall Men,648,"Fantasy,Horror,Thriller",A challenged man is stalked by tall phantoms i...,Jonathan Holbrook,"Dan Crisafulli, Kay Whitney, Richard Garcia, P...",2016,133,3.2,173,NaN,57.0
Dragonball Evolution,872,"Action,Adventure,Fantasy",The young warrior Son Goku sets out on a quest...,James Wong,"Justin Chatwin, James Marsters, Yun-Fat Chow, ...",2009,85,2.7,59512,9.35,45.0
Don't Fuck in the Woods,43,Horror,A group of friends are going on a camping trip...,Shawn Burkett,"Brittany Blanton, Ayse Howard, Roman Jossart,N...",2016,73,2.7,496,NaN,NaN
Disaster Movie,830,Comedy,"Over the course of one evening, an unsuspectin...",Jason Friedberg,"Carmen Electra, Vanessa Lachey,Nicole Parker, ...",2008,87,1.9,77207,14.17,15.0

In [24]:
# To Do: Re-sort the table in terms of 'Revenue(Millions)', in the increasing order and print out the first 5.
movie.sort_values(by = "Revenue (Millions)", ascending = True).head()

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
A Kind of Murder,232,"Crime,Drama,Thriller","In 1960s New York, Walter Stackhouse is a succ...",Andy Goddard,"Patrick Wilson, Jessica Biel, Haley Bennett, V...",2016,95,5.2,3305,0.00,50.0
Into the Forest,962,"Drama,Sci-Fi,Thriller","After a massive power outage, two sisters lear...",Patricia Rozema,"Ellen Page, Evan Rachel Wood, Max Minghella,Ca...",2015,101,5.9,10220,0.01,59.0
"Love, Rosie",678,"Comedy,Romance",Rosie and Alex have been best friends since th...,Christian Ditter,"Lily Collins, Sam Claflin, Christian Cooke, Ja...",2014,102,7.2,80415,0.01,44.0
Lovesong,322,Drama,The relationship between two friends deepens d...,So Yong Kim,"Riley Keough, Jena Malone, Jessie Ok Gray, Car...",2016,84,6.4,616,0.01,74.0
Wakefield,69,Drama,A man's nervous breakdown causes him to leave ...,Robin Swicord,"Bryan Cranston, Jennifer Garner, Beverly D'Ang...",2016,106,7.5,291,0.01,61.0

In [25]:
movie['Genre'].value_counts().head(10)

Action,Adventure,Sci-Fi       50
Drama                         48
Comedy,Drama,Romance          35
Comedy                        32
Drama,Romance                 31
Comedy,Drama                  27
Animation,Adventure,Comedy    27
Action,Adventure,Fantasy      27
Comedy,Romance                26
Crime,Drama,Thriller          24
Name: Genre, dtype: int64

In [26]:
movie[movie['Runtime (Minutes)'] <= 120]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
The Great Wall,6,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
Mindhorn,8,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
Passengers,10,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0
Moana,14,"Animation,Adventure,Comedy","In Ancient Polynesia, when a terrible curse in...",Ron Clements,"Auli'i Cravalho, Dwayne Johnson, Rachel House,...",2016,107,7.7,118151,248.75,81.0
Colossal,15,"Action,Comedy,Drama",Gloria is an out-of-work party girl forced to ...,Nacho Vigalondo,"Anne Hathaway, Jason Sudeikis, Austin Stowell,...",2016,109,6.4,8612,2.87,70.0
The Secret Life of Pets,16,"Animation,Adventure,Comedy",The quiet life of a terrier named Max is upend...,Chris Renaud,"Louis C.K., Eric Stonestreet, Kevin Hart, Lake...",2016,87,6.6,120259,368.31,61.0
Lion,19,"Biography,Drama",A five-year-old Indian boy gets lost on the st...,Garth Davis,"Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...",2016,118,8.1,102061,51.69,69.0
Arrival,20,"Drama,Mystery,Sci-Fi",When twelve mysterious spacecraft appear aroun...,Denis Villeneuve,"Amy Adams, Jeremy Renner, Forest Whitaker,Mich...",2016,116,8.0,340798,100.50,81.0
Gold,21,"Adventure,Drama,Thriller","Kenny Wells, a prospector desperate for a luck...",Stephen Gaghan,"Matthew McConaughey, Edgar Ramírez, Bryce Dall...",2016,120,6.7,19053,7.22,49.0
Hounds of Love,23,"Crime,Drama,Horror",A cold-blooded predatory couple while cruising...,Ben Young,"Emma Booth, Ashleigh Cummings, Stephen Curry,S...",2016,108,6.7,1115,NaN,72.0
Trolls,24,"Animation,Adventure,Comedy","After the Bergens invade Troll Village, Poppy,...",Walt Dohrn,"Anna Kendrick, Justin Timberlake,Zooey Deschan...",2016,92,6.5,38552,153.69,56.0
Independence Day: Resurgence,25,"Action,Adventure,Sci-Fi",Two decades after the first Independence Day i...,Roland Emmerich,"Liam Hemsworth, Jeff Goldblum, Bill Pullman,Ma...",2016,120,5.3,127553,103.14,32.0
Paris pieds nus,26,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,NaN,NaN
Dead Awake,28,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN
Bad Moms,29,Comedy,When three overworked and under-appreciated mo...,Jon Lucas,"Mila Kunis, Kathryn Hahn, Kristen Bell,Christi...",2016,100,6.2,66540,113.08,60.0
Assassin's Creed,30,"Action,Adventure,Drama",When Callum Lynch explores the memories of his...,Justin Kurzel,"Michael Fassbender, Marion Cotillard, Jeremy I...",2016,115,5.9,112813,54.65,36.0
Why Him?,31,Comedy,A holiday gathering threatens to go off the ra...,John Hamburg,"Zoey Deutch, James Franco, Tangie Ambrose,Cedr...",2016,111,6.3,48123,60.31,39.0
Nocturnal Animals,32,"Drama,Thriller",A wealthy art gallery owner is haunted by her ...,Tom Ford,"Amy Adams, Jake Gyllenhaal, Michael Shannon, A...",2016,116,7.5,126030,10.64,67.0
Deadpool,34,"Action,Adventure,Comedy",A fast-talking mercenary with a morbid sense o...,Tim Miller,"Ryan Reynolds, Morena Baccarin, T.J. Miller, E...",2016,108,8.0,627797,363.02,65.0
Resident Evil: The Final Chapter,35,"Action,Horror,Sci-Fi",Alice returns to where the nightmare began: Th...,Paul W.S. Anderson,"Milla Jovovich, Iain Glen, Ali Larter, Shawn R...",2016,107,5.6,46165,26.84,49.0
Doctor Strange,38,"Action,Adventure,Fantasy",While on a journey of physical and spiritual h...,Scott Derrickson,"Benedict Cumberbatch, Chiwetel Ejiofor, Rachel...",2016,115,7.6,293732,232.60,72.0
5- 25- 77,40,"Comedy,Drama","Alienated, hopeful-filmmaker Pat Johnson's epi...",Patrick Read Johnson,"John Francis Daley, Austin Pendleton, Colleen ...",2007,113,7.1,241,NaN,NaN
Sausage Party,41,"Animation,Adventure,Comedy",A sausage strives to discover the truth about ...,Greg Tiernan,"Seth Rogen, Kristen Wiig, Jonah Hill, Alistair...",2016,89,6.3,120690,97.66,66.0
Moonlight,42,Drama,"A chronicle of the childhood, adolescence and ...",Barry Jenkins,"Mahershala Ali, Shariff Earp, Duan Sanderson, ...",2016,111,7.5,135095,27.85,99.0
Don't Fuck in the Woods,43,Horror,A group of friends are going on a camping trip...,Shawn Burkett,"Brittany Blanton, Ayse Howard, Roman Jossart,N...",2016,73,2.7,496,NaN,NaN
The Founder,44,"Biography,Drama,History","The story of Ray Kroc, a salesman who turned t...",John Lee Hancock,"Michael Keaton, Nick Offerman, John Carroll Ly...",2016,115,7.2,37033,12.79,66.0
Lowriders,45,Drama,A young street artist in East Los Angeles is c...,Ricardo de Montreuil,"Gabriel Chavarria, Demián Bichir, Theo Rossi,T...",2016,99,6.3,279,4.21,57.0
Fallen,48,"Adventure,Drama,Fantasy",A young girl finds herself in a reform school ...,Scott Hicks,"Hermione Corfield, Addison Timlin, Joely Richa...",2016,91,5.6,5103,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
Into the Forest,962,"Drama,Sci-Fi,Thriller","After a massive power outage, two sisters lear...",Patricia Rozema,"Ellen Page, Evan Rachel Wood, Max Minghella,Ca...",2015,101,5.9,10220,0.01,59.0
The Other Boleyn Girl,963,"Biography,Drama,History",Two sisters contend for the affection of King ...,Justin Chadwick,"Natalie Portman, Scarlett Johansson, Eric Bana...",2008,115,6.7,88260,26.81,50.0
I Spit on Your Grave,964,"Crime,Horror,Thriller",A writer who is brutalized during her cabin re...,Steven R. Monroe,"Sarah Butler, Jeff Branson, Andrew Howard,Dani...",2010,108,6.3,60133,0.09,27.0
Custody,965,Drama,The lives of three women are unexpectedly chan...,James Lapine,"Viola Davis, Hayden Panettiere, Catalina Sandi...",2016,104,6.9,280,NaN,72.0
Wrecker,969,"Action,Horror,Thriller",Best friends Emily and Lesley go on a road tri...,Micheal Bafaro,"Anna Hutchison, Andrea Whitburn, Jennifer Koen...",2015,83,3.5,1210,NaN,37.0
Texas Chainsaw 3D,971,"Horror,Thriller",A young woman travels to Texas to collect an i...,John Luessenhop,"Alexandra Daddario, Tania Raymonde, Scott East...",2013,92,4.8,37060,34.33,62.0
Disturbia,972,"Drama,Mystery,Thriller",A teen living under house arrest becomes convi...,D.J. Caruso,"Shia LaBeouf, David Morse, Carrie-Anne Moss, S...",2007,105,6.9,193491,80.05,NaN
Scream 4,974,"Horror,Mystery","Ten years have passed, and Sidney Prescott, wh...",Wes Craven,"Neve Campbell, Courteney Cox, David Arquette, ...",2011,111,6.2,108544,38.18,52.0
My Big Fat Greek Wedding 2,976,"Comedy,Family,Romance",A Portokalos family secret brings the beloved ...,Kirk Jones,"Nia Vardalos, John Corbett, Michael Constantin...",2016,94,6.0,20966,59.57,37.0
Dark Places,977,"Drama,Mystery,Thriller",Libby Day was only eight years old when her fa...,Gilles Paquet-Brenner,"Charlize Theron, Nicholas Hoult, Christina Hen...",2015,113,6.2,31634,NaN,39.0
Amateur Night,978,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,NaN,38.0
It's Only the End of the World,979,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,NaN,48.0
The Skin I Live In,980,"Drama,Thriller","A brilliant plastic surgeon, haunted by past t...",Pedro Almodóvar,"Antonio Banderas, Elena Anaya, Jan Cornet,Mari...",2011,120,7.6,108772,3.19,70.0
Miracles from Heaven,981,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0
Annie,982,"Comedy,Drama,Family","A foster kid, who lives with her mean foster m...",Will Gluck,"Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...",2014,118,5.3,27312,85.91,33.0
Let's Be Cops,984,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.39,30.0
Max,985,"Adventure,Family",A Malinois dog that helped American Marines in...,Boaz Yakin,"Thomas Haden Church, Josh Wiggins, Luke Kleint...",2015,111,6.8,21405,42.65,47.0
Your Highness,986,"Adventure,Comedy,Fantasy","When Prince Fabious's bride is kidnapped, he g...",David Gordon Green,"Danny McBride, Natalie Portman, James Franco, ...",2011,102,5.6,87904,21.56,31.0
Final Destination 5,987,"Horror,Thriller",Survivors of a suspension-bridge collapse lear...,Steven Quale,"Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...",2011,92,5.9,88000,42.58,50.0
Endless Love,988,"Drama,Romance",The story of a privileged girl and a charismat...,Shana Feste,"Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...",2014,104,6.3,33688,23.39,30.0
Martyrs,989,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,NaN,89.0
Underworld: Rise of the Lycans,991,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.80,44.0
Take Me Home Tonight,993,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN
Resident Evil: Afterlife,994,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
Project X,995,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [27]:
# To Do: Extract the movie list whose 'Metascore' is bigger than 70.
movie[movie['Metascore'] >= 90]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
La La Land,7,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
Manchester by the Sea,22,Drama,A depressed uncle is asked to take care of his...,Kenneth Lonergan,"Casey Affleck, Michelle Williams, Kyle Chandle...",2016,137,7.9,134213,47.70,96.0
Moonlight,42,Drama,"A chronicle of the childhood, adolescence and ...",Barry Jenkins,"Mahershala Ali, Shariff Earp, Duan Sanderson, ...",2016,111,7.5,135095,27.85,99.0
Mad Max: Fury Road,68,"Action,Adventure,Sci-Fi",A woman rebels against a tyrannical ruler in p...,George Miller,"Tom Hardy, Charlize Theron, Nicholas Hoult, Zo...",2015,120,8.1,632842,153.63,90.0
12 Years a Slave,112,"Biography,Drama,History","In the antebellum United States, Solomon North...",Steve McQueen,"Chiwetel Ejiofor, Michael Kenneth Williams, Mi...",2013,134,8.1,486338,56.67,96.0
No Country for Old Men,137,"Crime,Drama,Thriller",Violence and mayhem ensue after a hunter stumb...,Ethan Coen,"Tommy Lee Jones, Javier Bardem, Josh Brolin, W...",2007,122,8.1,660286,74.27,91.0
Her,174,"Drama,Romance,Sci-Fi",A lonely writer develops an unlikely relations...,Spike Jonze,"Joaquin Phoenix, Amy Adams, Scarlett Johansson...",2013,126,8.0,390531,25.56,90.0
Spotlight,193,"Crime,Drama,History",The true story of how the Boston Globe uncover...,Tom McCarthy,"Mark Ruffalo, Michael Keaton, Rachel McAdams, ...",2015,128,8.1,268282,44.99,93.0
Paterson,208,"Comedy,Drama,Romance",A quiet observation of the triumphs and defeat...,Jim Jarmusch,"Adam Driver, Golshifteh Farahani, Nellie, Rizw...",2016,118,7.5,26089,2.14,90.0
Pan's Labyrinth,231,"Drama,Fantasy,War","In the falangist Spain of 1944, the bookish yo...",Guillermo del Toro,"Ivana Baquero, Ariadna Gil, Sergi López,Maribe...",2006,118,8.2,498879,37.62,98.0
Inside Out,242,"Animation,Adventure,Comedy",After young Riley is uprooted from her Midwest...,Pete Docter,"Amy Poehler, Bill Hader, Lewis Black, Mindy Ka...",2015,95,8.2,416689,356.45,94.0
There Will Be Blood,300,"Drama,History","A story of family, religion, hatred, oil and m...",Paul Thomas Anderson,"Daniel Day-Lewis, Paul Dano, Ciarán Hinds,Mart...",2007,158,8.1,400682,40.22,92.0
The Social Network,325,"Biography,Drama",Harvard student Mark Zuckerberg creates the so...,David Fincher,"Jesse Eisenberg, Andrew Garfield, Justin Timbe...",2010,120,7.7,510100,96.92,95.0
American Hustle,348,"Crime,Drama","A con man, Irving Rosenfeld, along with his se...",David O. Russell,"Christian Bale, Amy Adams, Bradley Cooper,Jenn...",2013,138,7.3,379088,150.12,90.0
Zero Dark Thirty,407,"Drama,History,Thriller",A chronicle of the decade-long hunt for al-Qae...,Kathryn Bigelow,"Jessica Chastain, Joel Edgerton, Chris Pratt, ...",2012,157,7.4,226661,95.72,95.0
Ratatouille,490,"Animation,Comedy,Family",A rat who can cook makes an unusual alliance w...,Brad Bird,"Brad Garrett, Lou Romano, Patton Oswalt,Ian Holm",2007,111,8.0,504039,206.44,96.0
Carol,502,"Drama,Romance",An aspiring photographer develops an intimate ...,Todd Haynes,"Cate Blanchett, Rooney Mara, Sarah Paulson, Ky...",2015,118,7.2,77995,0.25,95.0
Gravity,510,"Drama,Sci-Fi,Thriller",Two astronauts work together to survive after ...,Alfonso Cuarón,"Sandra Bullock, George Clooney, Ed Harris, Ort...",2013,91,7.8,622089,274.08,96.0
The Rise of the Krays,605,"Crime,Drama",Two brothers unleash a psychotic reign of terr...,Zackary Adler,"Matt Vael, Simon Cotton, Kevin Leslie, Olivia ...",2015,110,5.1,1630,6.53,90.0
Toni Erdmann,612,"Comedy,Drama",A practical joking father tries to reconnect w...,Maren Ade,"Sandra Hüller, Peter Simonischek, Michael Witt...",2016,162,7.6,24387,1.48,93.0
Megan Is Missing,634,"Drama,Horror,Thriller",Two teenage girls encounter an Internet child ...,Michael Goi,"Amber Perkins, Rachel Quinn, Dean Waite, Jael ...",2011,85,4.9,6683,NaN,94.0
Boyhood,657,Drama,"The life of Mason, from early childhood to his...",Richard Linklater,"Ellar Coltrane, Patricia Arquette, Ethan Hawke...",2014,165,7.9,286722,25.36,100.0
The Hurt Locker,673,"Drama,History,Thriller","During the Iraq War, a Sergeant recently assig...",Kathryn Bigelow,"Jeremy Renner, Anthony Mackie, Brian Geraghty,...",2008,131,7.6,352023,15.70,94.0
Toy Story 3,689,"Animation,Adventure,Comedy",The toys are mistakenly delivered to a day-car...,Lee Unkrich,"Tom Hanks, Tim Allen, Joan Cusack, Ned Beatty",2010,103,8.3,586669,414.98,92.0

In [28]:
# To Do: Extract the movie list whose 'Director' is 'Christopher Nolan'
movie[(movie['Director'] == 'Christopher Nolan')]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Interstellar,37,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
The Dark Knight,55,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
The Prestige,65,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66.0
Inception,81,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0
The Dark Knight Rises,125,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.0

#### 2.2.1 Pandas Exercise

To Do: Extract the movie list that meets below requirements:
- 1. Released after (and including) 2010 (key = 'Year')
- 2. Runtime is shorter than 150 minutes (key = 'Runtime (Minutes)')
- 3. Rating is above 8.0 (key = 'Rating') 
Print out only the first 3 movies.

In [29]:
movie[
    (movie['Year'] >= 2010) & (movie['Runtime (Minutes)'] <= 150) & (movie['Rating'] >= 8.0)
].head(3)

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
La La Land,7,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
Hacksaw Ridge,17,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0

### 2.3 Remove Missing Data
To represent missing data, pandas use np.nan. Pandas supports removal of missing data, which may deteriorate the performance of data science or machine learning model. In addition, most of data scientists and machine learning engineers remove missing data when they analyze data. 
- `isnull()` returns True or False, depending on the cell's null status. 
- `sum()` counts the number of nulls in each column.
- `dropna()` deletes any row that contains any single null value.
- `fillna(value)` : Fill missing value with the given values.

In [30]:
movie.isnull()

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,False,False,False,False,False,False,False,False,False,False,False
Prometheus,False,False,False,False,False,False,False,False,False,False,False
Split,False,False,False,False,False,False,False,False,False,False,False
Sing,False,False,False,False,False,False,False,False,False,False,False
Suicide Squad,False,False,False,False,False,False,False,False,False,False,False
The Great Wall,False,False,False,False,False,False,False,False,False,False,False
La La Land,False,False,False,False,False,False,False,False,False,False,False
Mindhorn,False,False,False,False,False,False,False,False,False,True,False
The Lost City of Z,False,False,False,False,False,False,False,False,False,False,False
Passengers,False,False,False,False,False,False,False,False,False,False,False
Fantastic Beasts and Where to Find Them,False,False,False,False,False,False,False,False,False,False,False
Hidden Figures,False,False,False,False,False,False,False,False,False,False,False
Rogue One,False,False,False,False,False,False,False,False,False,False,False
Moana,False,False,False,False,False,False,False,False,False,False,False
Colossal,False,False,False,False,False,False,False,False,False,False,False
The Secret Life of Pets,False,False,False,False,False,False,False,False,False,False,False
Hacksaw Ridge,False,False,False,False,False,False,False,False,False,False,False
Jason Bourne,False,False,False,False,False,False,False,False,False,False,False
Lion,False,False,False,False,False,False,False,False,False,False,False
Arrival,False,False,False,False,False,False,False,False,False,False,False
Gold,False,False,False,False,False,False,False,False,False,False,False
Manchester by the Sea,False,False,False,False,False,False,False,False,False,False,False
Hounds of Love,False,False,False,False,False,False,False,False,False,True,False
Trolls,False,False,False,False,False,False,False,False,False,False,False
Independence Day: Resurgence,False,False,False,False,False,False,False,False,False,False,False
Paris pieds nus,False,False,False,False,False,False,False,False,False,True,True
Bahubali: The Beginning,False,False,False,False,False,False,False,False,False,False,True
Dead Awake,False,False,False,False,False,False,False,False,False,False,True
Bad Moms,False,False,False,False,False,False,False,False,False,False,False
Assassin's Creed,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
Texas Chainsaw 3D,False,False,False,False,False,False,False,False,False,False,False
Disturbia,False,False,False,False,False,False,False,False,False,False,True
Rock of Ages,False,False,False,False,False,False,False,False,False,False,False
Scream 4,False,False,False,False,False,False,False,False,False,False,False
Queen of Katwe,False,False,False,False,False,False,False,False,False,False,False
My Big Fat Greek Wedding 2,False,False,False,False,False,False,False,False,False,False,False
Dark Places,False,False,False,False,False,False,False,False,False,True,False
Amateur Night,False,False,False,False,False,False,False,False,False,True,False
It's Only the End of the World,False,False,False,False,False,False,False,False,False,True,False
The Skin I Live In,False,False,False,False,False,False,False,False,False,False,False
Miracles from Heaven,False,False,False,False,False,False,False,False,False,False,False
Annie,False,False,False,False,False,False,False,False,False,False,False
Across the Universe,False,False,False,False,False,False,False,False,False,False,False
Let's Be Cops,False,False,False,False,False,False,False,False,False,False,False
Max,False,False,False,False,False,False,False,False,False,False,False
Your Highness,False,False,False,False,False,False,False,False,False,False,False
Final Destination 5,False,False,False,False,False,False,False,False,False,False,False
Endless Love,False,False,False,False,False,False,False,False,False,False,False
Martyrs,False,False,False,False,False,False,False,False,False,True,False
Selma,False,False,False,False,False,False,False,False,False,False,True
Underworld: Rise of the Lycans,False,False,False,False,False,False,False,False,False,False,False
Taare Zameen Par,False,False,False,False,False,False,False,False,False,False,False
Take Me Home Tonight,False,False,False,False,False,False,False,False,False,False,True
Resident Evil: Afterlife,False,False,False,False,False,False,False,False,False,False,False
Project X,False,False,False,False,False,False,False,False,False,False,False
Secret in Their Eyes,False,False,False,False,False,False,False,False,False,True,False
Hostel: Part II,False,False,False,False,False,False,False,False,False,False,False
Step Up 2: The Streets,False,False,False,False,False,False,False,False,False,False,False
Search Party,False,False,False,False,False,False,False,False,False,True,False
Nine Lives,False,False,False,False,False,False,False,False,False,False,False

In [31]:
movie.isnull().sum()

Rank                    0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [32]:
movie.shape

(1000, 11)

In [33]:
movie.fillna(value = 0)

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
The Great Wall,6,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
La La Land,7,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
Mindhorn,8,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,0.00,71.0
The Lost City of Z,9,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
Passengers,10,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0
Fantastic Beasts and Where to Find Them,11,"Adventure,Family,Fantasy",The adventures of writer Newt Scamander in New...,David Yates,"Eddie Redmayne, Katherine Waterston, Alison Su...",2016,133,7.5,232072,234.02,66.0
Hidden Figures,12,"Biography,Drama,History",The story of a team of female African-American...,Theodore Melfi,"Taraji P. Henson, Octavia Spencer, Janelle Mon...",2016,127,7.8,93103,169.27,74.0
Rogue One,13,"Action,Adventure,Sci-Fi",The Rebel Alliance makes a risky move to steal...,Gareth Edwards,"Felicity Jones, Diego Luna, Alan Tudyk, Donnie...",2016,133,7.9,323118,532.17,65.0
Moana,14,"Animation,Adventure,Comedy","In Ancient Polynesia, when a terrible curse in...",Ron Clements,"Auli'i Cravalho, Dwayne Johnson, Rachel House,...",2016,107,7.7,118151,248.75,81.0
Colossal,15,"Action,Comedy,Drama",Gloria is an out-of-work party girl forced to ...,Nacho Vigalondo,"Anne Hathaway, Jason Sudeikis, Austin Stowell,...",2016,109,6.4,8612,2.87,70.0
The Secret Life of Pets,16,"Animation,Adventure,Comedy",The quiet life of a terrier named Max is upend...,Chris Renaud,"Louis C.K., Eric Stonestreet, Kevin Hart, Lake...",2016,87,6.6,120259,368.31,61.0
Hacksaw Ridge,17,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0
Jason Bourne,18,"Action,Thriller",The CIA's most dangerous former operative is d...,Paul Greengrass,"Matt Damon, Tommy Lee Jones, Alicia Vikander,V...",2016,123,6.7,150823,162.16,58.0
Lion,19,"Biography,Drama",A five-year-old Indian boy gets lost on the st...,Garth Davis,"Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...",2016,118,8.1,102061,51.69,69.0
Arrival,20,"Drama,Mystery,Sci-Fi",When twelve mysterious spacecraft appear aroun...,Denis Villeneuve,"Amy Adams, Jeremy Renner, Forest Whitaker,Mich...",2016,116,8.0,340798,100.50,81.0
Gold,21,"Adventure,Drama,Thriller","Kenny Wells, a prospector desperate for a luck...",Stephen Gaghan,"Matthew McConaughey, Edgar Ramírez, Bryce Dall...",2016,120,6.7,19053,7.22,49.0
Manchester by the Sea,22,Drama,A depressed uncle is asked to take care of his...,Kenneth Lonergan,"Casey Affleck, Michelle Williams, Kyle Chandle...",2016,137,7.9,134213,47.70,96.0
Hounds of Love,23,"Crime,Drama,Horror",A cold-blooded predatory couple while cruising...,Ben Young,"Emma Booth, Ashleigh Cummings, Stephen Curry,S...",2016,108,6.7,1115,0.00,72.0
Trolls,24,"Animation,Adventure,Comedy","After the Bergens invade Troll Village, Poppy,...",Walt Dohrn,"Anna Kendrick, Justin Timberlake,Zooey Deschan...",2016,92,6.5,38552,153.69,56.0
Independence Day: Resurgence,25,"Action,Adventure,Sci-Fi",Two decades after the first Independence Day i...,Roland Emmerich,"Liam Hemsworth, Jeff Goldblum, Bill Pullman,Ma...",2016,120,5.3,127553,103.14,32.0
Paris pieds nus,26,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,0.00,0.0
Bahubali: The Beginning,27,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,0.0
Dead Awake,28,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,0.0
Bad Moms,29,Comedy,When three overworked and under-appreciated mo...,Jon Lucas,"Mila Kunis, Kathryn Hahn, Kristen Bell,Christi...",2016,100,6.2,66540,113.08,60.0
Assassin's Creed,30,"Action,Adventure,Drama",When Callum Lynch explores the memories of his...,Justin Kurzel,"Michael Fassbender, Marion Cotillard, Jeremy I...",2016,115,5.9,112813,54.65,36.0
...,...,...,...,...,...,...,...,...,...,...,...
Texas Chainsaw 3D,971,"Horror,Thriller",A young woman travels to Texas to collect an i...,John Luessenhop,"Alexandra Daddario, Tania Raymonde, Scott East...",2013,92,4.8,37060,34.33,62.0
Disturbia,972,"Drama,Mystery,Thriller",A teen living under house arrest becomes convi...,D.J. Caruso,"Shia LaBeouf, David Morse, Carrie-Anne Moss, S...",2007,105,6.9,193491,80.05,0.0
Rock of Ages,973,"Comedy,Drama,Musical",A small town girl and a city boy meet on the S...,Adam Shankman,"Julianne Hough, Diego Boneta, Tom Cruise, Alec...",2012,123,5.9,64513,38.51,47.0
Scream 4,974,"Horror,Mystery","Ten years have passed, and Sidney Prescott, wh...",Wes Craven,"Neve Campbell, Courteney Cox, David Arquette, ...",2011,111,6.2,108544,38.18,52.0
Queen of Katwe,975,"Biography,Drama,Sport",A Ugandan girl sees her world rapidly change a...,Mira Nair,"Madina Nalwanga, David Oyelowo, Lupita Nyong'o...",2016,124,7.4,6753,8.81,73.0
My Big Fat Greek Wedding 2,976,"Comedy,Family,Romance",A Portokalos family secret brings the beloved ...,Kirk Jones,"Nia Vardalos, John Corbett, Michael Constantin...",2016,94,6.0,20966,59.57,37.0
Dark Places,977,"Drama,Mystery,Thriller",Libby Day was only eight years old when her fa...,Gilles Paquet-Brenner,"Charlize Theron, Nicholas Hoult, Christina Hen...",2015,113,6.2,31634,0.00,39.0
Amateur Night,978,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,0.00,38.0
It's Only the End of the World,979,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,0.00,48.0
The Skin I Live In,980,"Drama,Thriller","A brilliant plastic surgeon, haunted by past t...",Pedro Almodóvar,"Antonio Banderas, Elena Anaya, Jan Cornet,Mari...",2011,120,7.6,108772,3.19,70.0
Miracles from Heaven,981,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0
Annie,982,"Comedy,Drama,Family","A foster kid, who lives with her mean foster m...",Will Gluck,"Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...",2014,118,5.3,27312,85.91,33.0
Across the Universe,983,"Drama,Fantasy,Musical",The music of the Beatles and the Vietnam War f...,Julie Taymor,"Evan Rachel Wood, Jim Sturgess, Joe Anderson, ...",2007,133,7.4,95172,24.34,56.0
Let's Be Cops,984,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.39,30.0
Max,985,"Adventure,Family",A Malinois dog that helped American Marines in...,Boaz Yakin,"Thomas Haden Church, Josh Wiggins, Luke Kleint...",2015,111,6.8,21405,42.65,47.0
Your Highness,986,"Adventure,Comedy,Fantasy","When Prince Fabious's bride is kidnapped, he g...",David Gordon Green,"Danny McBride, Natalie Portman, James Franco, ...",2011,102,5.6,87904,21.56,31.0
Final Destination 5,987,"Horror,Thriller",Survivors of a suspension-bridge collapse lear...,Steven Quale,"Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...",2011,92,5.9,88000,42.58,50.0
Endless Love,988,"Drama,Romance",The story of a privileged girl and a charismat...,Shana Feste,"Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...",2014,104,6.3,33688,23.39,30.0
Martyrs,989,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,0.00,89.0
Selma,990,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,0.0
Underworld: Rise of the Lycans,991,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.80,44.0
Taare Zameen Par,992,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0
Take Me Home Tonight,993,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,0.0
Resident Evil: Afterlife,994,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
Project X,995,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,0.00,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,0.00,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [34]:
movie.dropna(inplace = True)

In [35]:
movie.shape

(838, 11)

After removing missing data, the shape of movie dataFrame has changed, from (1000, 11) to (838, 11)

### 2.4 Merging Data
- `concat()` : Concatenation. Used to merge two or more pandas object.
- `merge()` : It is merged in the way of SQL.

In [36]:
df1 = pd.DataFrame(np.random.randn(10, 2))
df1

          0         1
0 -0.026906 -0.269447
1 -2.012701 -1.645426
2 -0.185034 -0.330895
3 -0.604065  0.799177
4 -0.771370  0.207680
5 -0.924487 -0.876124
6  0.798804 -0.716167
7 -0.372704 -0.672026
8 -1.392855 -0.199022
9 -0.159763  0.727479

In [37]:
df2 = pd.DataFrame(np.random.randn(10, 3))
df2

          0         1         2
0  1.590372  1.392244  0.749298
1 -2.083695 -2.444360 -0.342268
2  0.292361  1.330116 -0.593635
3  0.400332 -0.999294 -0.552435
4  0.751729  0.227846  0.346904
5  0.254000 -0.137756  0.380372
6 -0.958767  0.160100 -0.563122
7 -0.565781 -0.769643 -0.752707
8  0.978221 -1.861399  1.540701
9 -0.045132  0.253053  0.276611

In [38]:
pd.concat([df1, df2])

          0         1         2
0 -0.026906 -0.269447       NaN
1 -2.012701 -1.645426       NaN
2 -0.185034 -0.330895       NaN
3 -0.604065  0.799177       NaN
4 -0.771370  0.207680       NaN
5 -0.924487 -0.876124       NaN
6  0.798804 -0.716167       NaN
7 -0.372704 -0.672026       NaN
8 -1.392855 -0.199022       NaN
9 -0.159763  0.727479       NaN
0  1.590372  1.392244  0.749298
1 -2.083695 -2.444360 -0.342268
2  0.292361  1.330116 -0.593635
3  0.400332 -0.999294 -0.552435
4  0.751729  0.227846  0.346904
5  0.254000 -0.137756  0.380372
6 -0.958767  0.160100 -0.563122
7 -0.565781 -0.769643 -0.752707
8  0.978221 -1.861399  1.540701
9 -0.045132  0.253053  0.276611

In [39]:
pd.concat([df1, df2], axis = 1)

          0         1         0         1         2
0 -0.026906 -0.269447  1.590372  1.392244  0.749298
1 -2.012701 -1.645426 -2.083695 -2.444360 -0.342268
2 -0.185034 -0.330895  0.292361  1.330116 -0.593635
3 -0.604065  0.799177  0.400332 -0.999294 -0.552435
4 -0.771370  0.207680  0.751729  0.227846  0.346904
5 -0.924487 -0.876124  0.254000 -0.137756  0.380372
6  0.798804 -0.716167 -0.958767  0.160100 -0.563122
7 -0.372704 -0.672026 -0.565781 -0.769643 -0.752707
8 -1.392855 -0.199022  0.978221 -1.861399  1.540701
9 -0.159763  0.727479 -0.045132  0.253053  0.276611

In [40]:
demis = pd.DataFrame(
    {'Modules': ['Bioinformatics', 'Robotic Systems', 'Security', 'Compilers'], 'Demis' : [75, 97, 64, 81]}
)
demis

           Modules  Demis
0   Bioinformatics     75
1  Robotic Systems     97
2         Security     64
3        Compilers     81

In [41]:
sedol = pd.DataFrame(
    {'Modules': ['Bioinformatics', 'Robotic Systems', 'Security', 'Compilers'], 'Sedol' : [63, 78, 84, 95]})
sedol

           Modules  Sedol
0   Bioinformatics     63
1  Robotic Systems     78
2         Security     84
3        Compilers     95

In [42]:
pd.merge(demis, sedol, on = 'Modules')

           Modules  Demis  Sedol
0   Bioinformatics     75     63
1  Robotic Systems     97     78
2         Security     64     84
3        Compilers     81     95

In [43]:
#To Do: Define your own dataframe and use functions introducesd above to concatenate them.

### What to do next?
Below websites would be helpful for your further study on pandas library:
- [Pandas official website](https://pandas.pydata.org)
- [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html)
- [Data Wrangling with Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)